### PR TITLE
Explicitly use big endian in ICMP packet header

### PR DESCRIPTION
**Pull request by Henrycobaltech**
Sorry for the commit message, package -> packet

### CODE REVIEW

**Comment by Henrycobaltech** [comment]
Sure, I did some simplification on `IPPacket`
Also, I find that I should change the checksum function to big endian to make it consistent.

**Comment by lightsing** [comment]
Can you add unit test for these with travis-ci?

**Comment by Henrycobaltech** [comment]
Sorry, busy these days, maybe layer

**Comment by lightsing** [comment]
can you resubmit this pr?
this project is now under travis-ci

**Pull request closed without merging**
